"""Guardrails for code artifacts generated by the crew."""

import ast
import re
from typing import Any, Tuple

from crewai import Task
from crewai.tasks.task_output import TaskOutput

_FENCED_PYTHON = re.compile(
    r"```(?:python|py)?[ \t]*\r?\n(?P<source>.*?)```",
    flags=re.IGNORECASE | re.DOTALL,
)
_REVIEW_SECTIONS = ("summary", "blocking issues", "non-blocking issues")


def extract_python_source(raw: str) -> str:
    """Return Python source from raw or fenced model output."""
    match = _FENCED_PYTHON.search(raw)
    source = match.group("source") if match else raw
    return source.strip() + "\n"


def python_code_guardrail(output: TaskOutput) -> Tuple[bool, Any]:
    """Only permit syntactically valid Python to be persisted as source code."""
    source = extract_python_source(output.raw)
    try:
        ast.parse(source)
    except SyntaxError as exc:
        location = f"line {exc.lineno}" if exc.lineno else "unknown line"
        return False, f"Output is not valid Python ({location}): {exc.msg}"
    return True, source


def review_output_guardrail(output: TaskOutput) -> Tuple[bool, Any]:
    """Reject non-actionable review prose so CrewAI retries the reviewer."""
    raw = output.raw.strip()
    normalized = raw.lower()
    missing = [section for section in _REVIEW_SECTIONS if section not in normalized]
    if missing:
        return False, "Review must contain sections: Summary, Blocking Issues, and Non-Blocking Issues."

    repair_required = "repair_required" in normalized
    no_changes = "no_changes_required" in normalized
    if repair_required == no_changes:
        return False, "Review must state exactly one decision: REPAIR_REQUIRED or NO_CHANGES_REQUIRED."
    if repair_required and not all(
        field in normalized for field in ("severity", "artifact", "repair")
    ):
        return False, "A repair-required review must include severity, artifact, and repair instructions."
    if no_changes and "static review found no" not in normalized:
        return False, "A no-changes review must explicitly state that static review found no defects."
    return True, raw + "\n"


class GuardedPythonTask(Task):
    """Persist guardrail-transformed Python rather than the original LLM text."""

    def _save_file(self, result: object) -> None:
        if self.output is None:
            raise RuntimeError("Cannot save Python artifact without validated output")
        super()._save_file(self.output.raw)
