"""Guardrails for code artifacts generated by the crew."""

import ast
import re
from typing import Any, Tuple

from crewai import Task
from crewai.tasks.task_output import TaskOutput

_FENCED_PYTHON = re.compile(
    r"```(?:python|py)?[ \t]*\r?\n(?P<source>.*?)```",
    flags=re.IGNORECASE | re.DOTALL,
)

_FORBIDDEN_TEST_IMPORTS = {"gradio", "flask", "fastapi", "requests", "django"}

def make_python_guardrail(class_name: str | None = None, forbid_imports: set[str] | None = None):
    def _guardrail(output: TaskOutput) -> Tuple[bool, Any]:
        match = _FENCED_PYTHON.search(output.raw)
        source = (match.group("source") if match else output.raw).strip() + "\n"

        try:
            tree = ast.parse(source)
        except SyntaxError as exc:
            location = f"line {exc.lineno}" if exc.lineno else "unknown line"
            return False, f"Output is not valid Python ({location}): {exc.msg}"

        if class_name is not None:
            defined = [n.name for n in ast.walk(tree) if isinstance(n, ast.ClassDef)]
            if class_name not in defined:
                return (
                    False,
                    f"Output must define `class {class_name}` at module level. "
                    f"Found: {defined or 'none'}. Rewrite to export this class.",
                )

        if forbid_imports:
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    bad = [a.name for a in node.names if a.name.split(".")[0] in forbid_imports]
                elif isinstance(node, ast.ImportFrom):
                    bad = [node.module] if node.module and node.module.split(".")[0] in forbid_imports else []
                else:
                    continue
                if bad:
                    return (
                        False,
                        f"Forbidden import(s) found: {bad}. "
                        f"Test files must only use unittest and {'{module_name}'}.",
                    )

        return True, source

    return _guardrail


class GuardedPythonTask(Task):
    """Persist guardrail-transformed Python rather than the original LLM text."""

    def _save_file(self, result: object) -> None:
        if self.output is None:
            raise RuntimeError("Cannot save Python artifact without validated output")
        super()._save_file(self.output.raw)